# Generated by Django 3.1.7 on 2021-03-09 01:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('nombre', models.CharField(max_length=30)),
                ('especialidad', models.CharField(max_length=50)),
                ('matricula', models.IntegerField(primary_key=True, serialize=False)),
                ('cuit', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('dni', models.IntegerField(null=True)),
                ('obra_social', models.CharField(max_length=15)),
                ('n_obra_social', models.IntegerField(null=True)),
                ('fecha_nacimiento', models.DateField(null=True)),
                ('telefono', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Turnos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField()),
                ('matricula_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turnos.medico')),
                ('paciente_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='turnos.paciente')),
            ],
        ),
        migrations.AddField(
            model_name='paciente',
            name='medico',
            field=models.ManyToManyField(through='turnos.Turnos', to='turnos.Medico'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
